{
  "timestamp": "2025-05-20T02:30:38.346561",
  "endpoints": {},
  "issues": [
    "Connection error: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /docs (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x105043e00>, 'Connection to localhost timed out. (connect timeout=None)'))"
  ],
  "api_running": false
}